npm test
> nextn@0.1.0 test
> jest

 FAIL  src/components/link-group/__tests__/link-group-form-dialog.test.tsx
  ● LinkGroupFormDialog Component › calls onSubmit with form data when form is valid (create mode)

    TypeError: crypto.randomUUID is not a function

      82 |   const handleFormSubmit = (data: LinkGroupFormData) => {
      83 |     onSubmit({
    > 84 |       id: initialData?.id || crypto.randomUUID(),
         |                                     ^
      85 |       ...data,
      86 |     });
      87 |     onClose();

      at handleFormSubmit (src/components/link-group/link-group-form-dialog.tsx:84:37)
      at isSubmitted (node_modules/react-hook-form/src/logic/createFormControl.ts:1267:9)

  ● LinkGroupFormDialog Component › calls onSubmit with form data when form is valid (create mode)

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

    Ignored nodes: comments, script, style
    <html>
      <head />
      <body
        data-scroll-locked="1"
        style="pointer-events: none;"
      >
        <span
          aria-hidden="true"
          data-aria-hidden="true"
          data-radix-focus-guard=""
          style="outline: none; opacity: 0; position: fixed; pointer-events: none;"
          tabindex="0"
        />
        <div
          aria-hidden="true"
          data-aria-hidden="true"
        />
        <div
          aria-hidden="true"
          class="fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0"
          data-aria-hidden="true"
          data-state="open"
          data-testid="dialog-overlay"
          style="pointer-events: auto;"
        />
        <div
          aria-describedby="radix-:rh:"
          aria-labelledby="radix-:rg:"
          class="fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg sm:max-w-[525px]"
          data-state="open"
          id="radix-:rf:"
          role="dialog"
          style="pointer-events: auto;"
          tabindex="-1"
        >
          <div
            class="flex flex-col space-y-1.5 text-center sm:text-left"
          >
            <h2
              class="text-lg font-semibold leading-none tracking-tight"
              id="radix-:rg:"
            >
              Create
               Link Group
            </h2>
            <p
              class="text-sm text-muted-foreground"
              id="radix-:rh:"
            >
              Add a new
               link group to quickly open sets of URLs.
            </p>
          </div>
          <form
            class="space-y-6"
          >
            <div
              data-joyride="group-form-name-input"
            >
              <label
                class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                for="name"
              >
                Group Name
              </label>
              <input
                class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm mt-1"
                id="name"
                name="name"
              />
            </div>
            <div
              data-joyride="group-form-icon-picker"
            >
              <label
                class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                for="icon-picker"
              >
                Icon
              </label>
              <button
                data-testid="icon-picker-input"
              >
                NewIcon
              </button>
              <p
                class="text-xs text-muted-foreground mt-1"
              >
                Search and select a
                <a
                  class="underline"
                  href="https://lucide.dev/icons/"
                  rel="noopener noreferrer"
                  target="_blank"
                >
                  Lucide icon
                </a>
                .
              </p>
            </div>
            <div
              data-joyride="group-form-urls-input"
            >
              <label
                class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                URLs
              </label>
              <div>
                <input
                  data-testid="url-input-0"
                  value="http://newurl.com"
                />
                <button>
                  Add URL
                </button>
              </div>
            </div>
            <div
              class="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2 pt-2"
            >
              <button
                class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2"
                type="button"
              >
                Cancel
              </button>
              <button
                class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2"
                data-joyride="group-form-save-button"
                type="submit"
              >
                Save Group
              </button>
            </div>
          </form>
          <button
            class="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground"
            type="button"
          >
            <svg
              class="lucide lucide-x h-4 w-4"
              fill="none"
              height="24"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M18 6 6 18"
              />
              <path
                d="m6 6 12 12"
              />
            </svg>
            <span
              class="sr-only"
            >
              Close
            </span>
          </button>
        </div>
        <span
          aria-hidden="true"
          data-aria-hidden="true"
          data-radix-focus-guard=""
          style="outline: none; opacity: 0; position: fixed; pointer-events: none;"
          tabindex="0"
        />
      </body>
    </html>

      132 |
      133 |     await waitFor(() => {
    > 134 |         expect(mockOnSubmit).toHaveBeenCalledTimes(1);
          |                              ^
      135 |     });
      136 |     expect(mockOnSubmit).toHaveBeenCalledWith(expect.objectContaining({
      137 |       name: 'My New Group',

      at src/components/link-group/__tests__/link-group-form-dialog.test.tsx:134:30
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:47:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:124:77)
      at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:118:16)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)

  ● LinkGroupFormDialog Component › calls onSubmit with updated form data when form is valid (edit mode)

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 2

    Ignored nodes: comments, script, style
    <html>
      <head />
      <body
        data-scroll-locked="1"
        style="pointer-events: none;"
      >
        <span
          aria-hidden="true"
          data-aria-hidden="true"
          data-radix-focus-guard=""
          style="outline: none; opacity: 0; position: fixed; pointer-events: none;"
          tabindex="0"
        />
        <div
          aria-hidden="true"
          data-aria-hidden="true"
        />
        <div
          aria-hidden="true"
          class="fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0"
          data-aria-hidden="true"
          data-state="open"
          data-testid="dialog-overlay"
          style="pointer-events: auto;"
        />
        <div
          aria-describedby="radix-:rk:"
          aria-labelledby="radix-:rj:"
          class="fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg sm:max-w-[525px]"
          data-state="open"
          id="radix-:ri:"
          role="dialog"
          style="pointer-events: auto;"
          tabindex="-1"
        >
          <div
            class="flex flex-col space-y-1.5 text-center sm:text-left"
          >
            <h2
              class="text-lg font-semibold leading-none tracking-tight"
              id="radix-:rj:"
            >
              Edit
               Link Group
            </h2>
            <p
              class="text-sm text-muted-foreground"
              id="radix-:rk:"
            >
              Modify your
               link group to quickly open sets of URLs.
            </p>
          </div>
          <form
            class="space-y-6"
          >
            <div
              data-joyride="group-form-name-input"
            >
              <label
                class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                for="name"
              >
                Group Name
              </label>
              <input
                class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm mt-1"
                id="name"
                name="name"
              />
            </div>
            <div
              data-joyride="group-form-icon-picker"
            >
              <label
                class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                for="icon-picker"
              >
                Icon
              </label>
              <button
                data-testid="icon-picker-input"
              >
                NewIcon
              </button>
              <p
                class="text-xs text-muted-foreground mt-1"
              >
                Search and select a
                <a
                  class="underline"
                  href="https://lucide.dev/icons/"
                  rel="noopener noreferrer"
                  target="_blank"
                >
                  Lucide icon
                </a>
                .
              </p>
            </div>
            <div
              data-joyride="group-form-urls-input"
            >
              <label
                class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                URLs
              </label>
              <div>
                <input
                  data-testid="url-input-0"
                  value="http://updatedurl.com"
                />
                <button>
                  Add URL
                </button>
              </div>
            </div>
            <div
              class="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2 pt-2"
            >
              <button
                class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2"
                type="button"
              >
                Cancel
              </button>
              <button
                class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2"
                data-joyride="group-form-save-button"
                type="submit"
              >
                Save Group
              </button>
            </div>
          </form>
          <button
            class="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground"
            type="button"
          >
            <svg
              class="lucide lucide-x h-4 w-4"
              fill="none"
              height="24"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M18 6 6 18"
              />
              <path
                d="m6 6 12 12"
              />
            </svg>
            <span
              class="sr-only"
            >
              Close
            </span>
          </button>
        </div>
        <span
          aria-hidden="true"
          data-aria-hidden="true"
          data-radix-focus-guard=""
          style="outline: none; opacity: 0; position: fixed; pointer-events: none;"
          tabindex="0"
        />
      </body>
    </html>

      165 |
      166 |     await waitFor(() => {
    > 167 |         expect(mockOnSubmit).toHaveBeenCalledTimes(1);
          |                              ^
      168 |     });
      169 |
      170 |     expect(mockOnSubmit).toHaveBeenCalledWith(expect.objectContaining({

      at src/components/link-group/__tests__/link-group-form-dialog.test.tsx:167:30
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:47:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:124:77)
      at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:118:16)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)

 PASS  src/components/ui/__tests__/confirmation-dialog.test.tsx
 PASS  src/components/ui/__tests__/button.test.tsx
 PASS  src/lib/__tests__/utils.test.ts

Test Suites: 1 failed, 3 passed, 4 total
Tests:       2 failed, 40 passed, 42 total
Snapshots:   0 total
Time:        7.809 s, estimated 9 s
Ran all test suites.